# fly.toml file generated for stardeveloper on 2022-09-09T22:36:42+02:00

app = "stardeveloper"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  RACK_ENV = "production"
  APP_NAME="stardeveloper"
  DATABASE_URL="sqlite://stardeveloper.db"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
